name: Deploy to SFTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Add SFTP Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          # Add Domeneshop’s SFTP server fingerprint (RSA)
          echo "sftp.domeneshop.no ssh-rsa RHq/z1yca8CXL89ZORqN6u3CovMnUo1QTEAnYNTyBxA=" > ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Deploy to SFTP Server via lftp
        run: |
          lftp -u "${{ secrets.DOMENESHOP_SFTP_USERNAME }},${{ secrets.DOMENESHOP_SFTP_PASSWORD }}" sftp://sftp.domeneshop.no -e "set sftp:connect-program \"ssh -o StrictHostKeyChecking=yes -o UserKnownHostsFile=~/.ssh/known_hosts -o PreferredAuthentications=password -o HostKeyAlgorithms=+ssh-rsa -p 22\"; mirror -R --delete --verbose --exclude-glob .git* --exclude-glob secrets.json --exclude-glob '*.env' ./ /www; quit"
