name: Deploy to Domeneshop

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.DOMENESHOP_SFTP_HOST }}
          username: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          ssh_private_key: ${{ secrets.DOMENESHOP_SSH_PRIVATE_KEY }}
          local_path: './*'
          remote_path: '/www'
          port: 22
          sftpArgs: '-o ConnectTimeout=5'
