name: Deploy to Domeneshop

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup and Verify Known Hosts
        run: |
          # Create SSH directory if it doesn't exist
          mkdir -p ~/.ssh
          echo "Scanning scp.domeneshop.no for its RSA public key..."
          # Scan the server and store its key temporarily
          ssh-keyscan -t rsa scp.domeneshop.no > ~/.ssh/known_hosts.tmp 2>/dev/null

          # Extract the fingerprint from the temporary file
          ACTUAL_FINGERPRINT=$(ssh-keygen -lf ~/.ssh/known_hosts.tmp | awk '{print $2}')
          echo "Actual fingerprint: $ACTUAL_FINGERPRINT"
          echo "Expected fingerprint: ${{ secrets.SSH_FINGERPRINT }}"

          if [ "$ACTUAL_FINGERPRINT" != "${{ secrets.SSH_FINGERPRINT }}" ]; then
            echo "Fingerprint mismatch! Aborting deployment."
            exit 1
          fi

          # Use the verified known_hosts file for SFTP
          mv ~/.ssh/known_hosts.tmp ~/.ssh/known_hosts
        shell: bash

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Deploy via lftp Mirror (SFTP)
        env:
          DOMENESHOP_SFTP_USERNAME: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          DOMENESHOP_SFTP_PASSWORD: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
        run: |
          # Tell lftp to use our verified known_hosts file
          export SFTP_KNOWN_HOSTS=~/.ssh/known_hosts
          # Connect to the SFTP server (using scp.domeneshop.no as required) and mirror the local repo to /www.
          lftp -u "$DOMENESHOP_SFTP_USERNAME,$DOMENESHOP_SFTP_PASSWORD" sftp://scp.domeneshop.no <<'EOF'
          mirror -R --delete --verbose ./ /www
          quit
EOF
