name: Deploy to Domeneshop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the entire repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up SSH known_hosts so that we securely connect to the remote server.
      - name: Set up SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "Fetching SSH fingerprint for ${{ secrets.DOMENESHOP_SFTP_HOST }}..."
          ssh-keyscan -H "${{ secrets.DOMENESHOP_SFTP_HOST }}" >> ~/.ssh/known_hosts || {
            echo "Error: Failed to fetch SSH fingerprint." >&2
            exit 1
          }
          echo "SSH known_hosts updated."

      # 3. Ensure the remote 'www' folder exists.
      #    According to Domeneshop’s documentation, the web‐accessible files must reside in the "www" folder.
      - name: Ensure remote www folder exists
        env:
          SFTP_HOST: ${{ secrets.DOMENESHOP_SFTP_HOST }}
          SFTP_USER: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          SFTP_PASS: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
        run: |
          echo "Ensuring remote www folder exists on $SFTP_HOST..."
          sudo apt-get update -qq && sudo apt-get install -y sshpass > /dev/null
          sshpass -p "$SFTP_PASS" ssh -o StrictHostKeyChecking=yes "$SFTP_USER@$SFTP_HOST" 'mkdir -p www' || {
            echo "Error: Failed to create remote www folder." >&2
            exit 1
          }
          echo "Remote www folder verified."

      # 4. Deploy all repository files and directories (with their structure)
      #    This will copy everything from the repo root into the remote "www" folder.
      - name: Deploy repository content to remote www folder
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DOMENESHOP_SFTP_HOST }}
          username: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          password: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
          port: 22
          source: "."
          target: "www/"
