name: Deploy to SFTP Server

on:
  push:
    branches:
      - main  # Triggers deployment on push to the 'main' branch

jobs:
  deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Domeneshop SFTP Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "sftp.domeneshop.no ssh-rsa RHq/z1yca8CXL89ZORqN6u3CovMnUo1QTEAnYNTyBxA=" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          server: sftp.domeneshop.no
          username: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          password: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
          port: 22
          local_path: './*'
          remote_path: '/www'
