name: Deploy to Domeneshop via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up known_hosts with pre-approved fingerprint(s).
      # You must add the complete known_hosts entry (the server’s public key in known_hosts format)
      # to the secret DOMENESHOP_KNOWN_HOSTS. This file should contain the expected fingerprints as provided by Domeneshop.
      - name: Set up known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOMENESHOP_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Step 3: Deploy files via SFTP using appleboy's sftp-action.
      - name: Deploy via SFTP
        uses: appleboy/sftp-action@master
        with:
          host: ${{ secrets.DOMENESHOP_SFTP_HOST }}
          username: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          password: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
          port: 22
          local: ./
          remote: /www

      # Step 4: Log success.
      - name: Deployment Success Logging
        if: ${{ success() }}
        run: echo "Deployment completed successfully."

      # Step 5: Log errors if any.
      - name: Deployment Error Logging
        if: ${{ failure() }}
        run: echo "Deployment failed. Please check the logs for details."
