name: Deploy to Domeneshop

on:
  push:
    branches:
      - main

# Limit permissions to minimum required
permissions:
  contents: read
  deployments: write

# Ensure only one deployment runs at a time
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Create Remote Directories (if needed)
        run: |
          lftp -u "${{ secrets.DOMENESHOP_FTP_USERNAME }},${{ secrets.DOMENESHOP_FTP_PASSWORD }}" ftp://ftp.domeneshop.no -e "
          set ftp:ssl-allow no;
          mkdir -p /www/static /www/templates;
          bye"

      - name: Deploy Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.domeneshop.no
          username: ${{ secrets.DOMENESHOP_FTP_USERNAME }}
          password: ${{ secrets.DOMENESHOP_FTP_PASSWORD }}
          protocol: ftp
          server-dir: /www/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            .env
            __pycache__/**
            *.pyc
            **/.env*
            **/*.key
            **/*.pem
            **/secrets.*