name: Deploy to Domeneshop via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.DOMENESHOP_SFTP_HOST }}" >> ~/.ssh/known_hosts

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy files via SFTP
        env:
          SSHPASS: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
        run: |
          sshpass -e sftp -oBatchMode=no -o StrictHostKeyChecking=yes -P 22 ${{ secrets.DOMENESHOP_SFTP_USERNAME }}@${{ secrets.DOMENESHOP_SFTP_HOST }} <<'EOF'
cd www
lcd .
put -r *
quit
EOF
