name: Deploy to Domeneshop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Add SSH fingerprint to known_hosts
        env:
          SFTP_HOST: ${{ secrets.DOMENESHOP_SFTP_HOST }}
          SSH_FINGERPRINT: ${{ secrets.SSH_FINGERPRINT }}
        run: |
          echo "Ensuring SSH directory exists..."
          mkdir -p ~/.ssh

          echo "Fetching SSH key from server..."
          ssh-keyscan -H $SFTP_HOST > ~/.ssh/known_hosts

          echo "Received SSH fingerprint from server:"
          ssh-keygen -lf ~/.ssh/known_hosts | tee received_fingerprint.log

          echo "Expected SSH fingerprint: $SSH_FINGERPRINT"

          echo "Verifying fingerprint..."
          if ! grep -q "$SSH_FINGERPRINT" received_fingerprint.log; then
            echo "Error: Host key does not match expected fingerprint!"
            exit 1
          fi
          echo "Fingerprint verified."

      - name: Deploy Files from www
        env:
          SFTP_HOST: ${{ secrets.DOMENESHOP_SFTP_HOST }}
          SFTP_USER: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          SFTP_PASS: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
        run: |
          echo "Uploading files from www/ to /www..."
          lftp -u "$SFTP_USER","$SFTP_PASS" sftp://$SFTP_HOST <<EOF
            # Upload new and changed files from local www/ to remote /www
            mirror -R --verbose --only-newer --parallel=4 www/ /www

            # Remove files on server that were deleted locally
            cd /www
            mirror -e --delete --verbose www/ .
            bye
          EOF