name: Deploy to Domeneshop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via SFTP
        env:
          SFTP_HOST: ${{ secrets.DOMENESHOP_SFTP_HOST }}
          SFTP_USER: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          SFTP_PASS: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
          SSH_FINGERPRINT: ${{ secrets.SSH_FINGERPRINT }}
        run: |
          echo "Verifying SSH fingerprint..."
          ssh-keyscan -H $SFTP_HOST >> known_hosts
          if ! grep -q "$SSH_FINGERPRINT" known_hosts; then
            echo "Error: Host key does not match expected fingerprint!"
            exit 1
          fi

          echo "Deploying files..."
          lftp -c "
            open -u $SFTP_USER,$SFTP_PASS sftp://$SFTP_HOST
            mirror -R --delete --verbose ./ /www
            bye
          "

