name: Deploy to SFTP Server

on:
  push:
    branches:
      - main  # Triggers deployment on push to the 'main' branch

jobs:
  deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          server: sftp.domeneshop.no
          username: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          password: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
          port: 22
          local_path: './*'
          remote_path: '/www'
          sftp_only: true  # ✅ Force SFTP-only mode to prevent SSH execution
