      - name: Deploy via SFTP
        env:
          SFTP_HOST: ${{ secrets.DOMENESHOP_SFTP_HOST }}
          SFTP_USER: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          SFTP_PASS: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
        run: |
          echo "Deploying files..."
          lftp -c "
            open -u $SFTP_USER,$SFTP_PASS sftp://$SFTP_HOST
            mirror -R --delete --verbose ./ /www \
              --exclude .git/ \
              --exclude .gitignore \
              --exclude README.md \
              --exclude LICENSE \
              --exclude *.yml \
              --exclude *.sh \
              --exclude node_modules/ \
              --exclude package.json \
              --exclude package-lock.json \
              --exclude yarn.lock \
              --exclude tests/ \
              --exclude __tests__/ \
              --exclude coverage/ \
              --exclude .vscode/ \
              --exclude .idea/ \
              --exclude *.log \
              --exclude .DS_Store \
              --exclude Thumbs.db \
              --exclude .*  # Exclude hidden files unless explicitly needed
            bye
          "
