name: Deploy to Domeneshop

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ensure SSH Known Hosts is Updated
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H sftp.domeneshop.no >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "SSH key fingerprint added to known hosts."

      - name: Ensure Directories Exist on Remote
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          echo "Testing SFTP connection..."
          lftp -d -u "${{ secrets.DOMENESHOP_SFTP_USERNAME }},${{ secrets.DOMENESHOP_SFTP_PASSWORD }}" sftp://sftp.domeneshop.no -e "
          set sftp:auto-confirm yes;
          set sftp:connect-program 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null';
          set net:max-retries 2;
          set net:reconnect-interval-base 5;
          open -p 22 -s sftp://sftp.domeneshop.no;
          ls /www;
          mkdir -p /www/static /www/templates;
          bye"

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: sftp.domeneshop.no
          username: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          password: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
          local_path: './*'
          remote_path: '/www'
          port: 22
          sftp_only: true
          sftpArgs: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=no -o PasswordAuthentication=yes -o ConnectTimeout=5'
