name: Deploy to Domeneshop

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Create Remote Directories (if needed)
        run: |
          lftp -u "${{ secrets.DOMENESHOP_SFTP_USERNAME }},${{ secrets.DOMENESHOP_SFTP_PASSWORD }}" sftp://sftp.domeneshop.no -e "
          set sftp:auto-confirm yes;
          set sftp:connect-program 'ssh -o StrictHostKeyChecking=no';
          open -p 22 -s sftp://sftp.domeneshop.no;
          mkdir -p /www/static /www/templates;
          bye"

      - name: Deploy Files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: sftp.domeneshop.no
          username: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          password: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
          local_path: './*'
          remote_path: '/www'
          port: 22
          sftp_only: true
          sftpArgs: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
