name: Deploy to Domeneshop via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Preconfigure SSH to verify the server certificate using the provided fingerprints.
      - name: Set up known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOMENESHOP_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Deploy using SamKirkland's FTP-Deploy-Action, which supports SFTP,
      # handles remote folder creation, and leverages your secure secrets.
      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          ftp-server: sftp://${{ secrets.DOMENESHOP_SFTP_HOST }}
          ftp-username: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          ftp-password: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
          protocol: sftp
          local-dir: ./
          server-dir: www

      - name: Deployment Success Logging
        if: ${{ success() }}
        run: echo "Deployment completed successfully."

      - name: Deployment Error Logging
        if: ${{ failure() }}
        run: echo "Deployment failed. Please check the logs for details."
