name: Deploy to Domeneshop

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ensure Directories Exist on Remote
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          echo "Testing SFTP connection..."
          lftp -d -u "${{ secrets.DOMENESHOP_SFTP_USERNAME }},${{ secrets.DOMENESHOP_SFTP_PASSWORD }}" sftp://${{ secrets.DOMENESHOP_SFTP_HOST }} -e "
          set sftp:auto-confirm yes;
          set ftp:passive-mode off;   # Switch to active mode if passive isn't working
          set net:timeout 15;
          set net:max-retries 2;
          set net:reconnect-interval-base 5;
          set net:reconnect-interval-multiplier 1;
          open -p 22 -s sftp://${{ secrets.DOMENESHOP_SFTP_HOST }};
          ls /www;   # Debug: check if /www is accessible
          mkdir -p /www/static /www/templates;
          bye"

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.DOMENESHOP_SFTP_HOST }}
          username: ${{ secrets.DOMENESHOP_SFTP_USERNAME }}
          password: ${{ secrets.DOMENESHOP_SFTP_PASSWORD }}
          local_path: './*'
          remote_path: '/www'
          port: 22
          sftp_only: true
          sftpArgs: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=no -o PasswordAuthentication=yes -o ConnectTimeout=5'
