name: Deploy to Domeneshop

on:
  push:
    branches:
      - main
    paths:
      - 'www/**'

# Limit permissions to minimum required
permissions:
  contents: read
  deployments: write

# Ensure only one deployment runs at a time
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Required Packages
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.domeneshop.no
          username: ${{ secrets.DOMENESHOP_FTP_USERNAME }}
          password: ${{ secrets.DOMENESHOP_FTP_PASSWORD }}
          protocol: ftp
          server-dir: /www/
          local-dir: ./www/
          include: |
            **/*.html
            **/*.css
            **/*.js
            **/*.png
            **/*.jpg
            **/*.jpeg
            **/*.gif
            **/*.svg
            **/*.ico
            **/*.txt
            **/*.xml
            **/*.pdf
            **/*.webp